FROM python:3.12-slim
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/client.py .
COPY src/gui ./gui

#criar endpoints pro javascript dinamicamente com base nas variaveis setadas no docker
COPY set_endpoints.sh .
RUN chmod +x set_endpoints.sh
CMD ["./set_endpoints.sh"]
