FROM python:3.12-slim
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/client.py .
COPY src/gui ./gui

#criar endpoints pro javascript dinamicamente
COPY set_js_endpoints.sh .
RUN chmod +x set_js_endpoints.sh
CMD ["./set_js_endpoints.sh"]
